#!/bin/bash

options=(
    style=round
    width=2.0
    hidpi=on
    active_color=0xff9ed072
    inactive_color=0xff7f8490
    background_color=0xc02c2e34
    order=above
    blacklist="VLC"
)

borders "${options[@]}"
